package com.eripe14.houses.house.region.protection;

public enum ProtectionCause {

    CANCEL_EVENT_WITH_MESSAGE,
    NOT_CANCEL_EVENT_WITH_MESSAGE,
    CANCEL_EVENT_WITHOUT_MESSAGE,
    NOT_CANCEL_EVENT_WITHOUT_MESSAGE,
    RENOVATE_COMPLETE,
    RENOVATE_MAJOR,
    RENOVATE_NON_INTERFERING

}